//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJoJoSports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prjJoJoSports_dbEntities : DbContext
    {
        public prjJoJoSports_dbEntities()
            : base("name=prjJoJoSports_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<t訂閱名單> t訂閱名單 { get; set; }
        public virtual DbSet<t留言板回覆> t留言板回覆 { get; set; }
        public virtual DbSet<t參加名單> t參加名單 { get; set; }
        public virtual DbSet<t開團> t開團 { get; set; }
        public virtual DbSet<t開團留言板> t開團留言板 { get; set; }
        public virtual DbSet<t開團評價> t開團評價 { get; set; }
        public virtual DbSet<t會員狀態> t會員狀態 { get; set; }
        public virtual DbSet<t會員資料> t會員資料 { get; set; }
        public virtual DbSet<t運動項目> t運動項目 { get; set; }
        public virtual DbSet<t縣市名稱> t縣市名稱 { get; set; }
    }
}
