//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJoJoSports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t會員資料
    {
        public int f會員資料編號 { get; set; }
        public string f帳號 { get; set; }
        public string f密碼 { get; set; }
        public string f確認密碼 { get; set; }
        public string f姓名 { get; set; }
        public string f名稱 { get; set; }
        public string f性別 { get; set; }
        public string f電話 { get; set; }
        public Nullable<System.DateTime> f生日 { get; set; }
    }
}
