//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJoJoSports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t開團
    {
        public int f開團編號 { get; set; }
        public string f團長名稱 { get; set; }
        public string f運動項目名稱 { get; set; }
        public string f標題 { get; set; }
        public string f備註 { get; set; }
        public Nullable<System.DateTime> f活動開始時間 { get; set; }
        public Nullable<System.DateTime> f活動結束時間 { get; set; }
        public Nullable<System.DateTime> f貼文發布時間 { get; set; }
        public Nullable<System.DateTime> f報名截止時間 { get; set; }
        public Nullable<int> f人數上限 { get; set; }
        public string f活動地點 { get; set; }
        public Nullable<decimal> f緯度 { get; set; }
        public Nullable<decimal> f經度 { get; set; }
        public string f狀態 { get; set; }
    }
}
